title: The World of Digital AwesoMeness (DAMs)! 🚀
author: Rudolf Traunmüller
description: As I dive into the world of programming cloud services around digital asset management, I'll be chronicling my experiences, challenges, and the fascinating things I learn along the way.
theme: "jekyll-theme-yat"
